apiVersion: apps/v1
kind: Deployment
metadata:
  name: picture-label-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: picture-label
  template:
    metadata:
      labels:
        app: picture-label
    spec:
      containers:
        - name: picture-label-backend
          image: gcr.io/gcp-lectures-306517/picture-label-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: "GOOGLE_APPLICATION_CREDENTIALS"
              value: "/var/run/secret/cloud.google.com/service-account.json"
            - name: "NODE_ENV"
              value: "production"
          volumeMounts:
            - name: "service-account"
              mountPath: "/var/run/secret/cloud.google.com"
      volumes:
        - name: "service-account"
          secret:
            secretName: "picture-label-secret"
